# The main jupyter notebook for group three

> each will take this file and change it according to the question

## What is done in this notebook

- Data Loading and Initial Exploration:
    - Load the dataset into a pandas DataFrame.
    - Display the first 5 rows and check the data types of all columns.
    - Identify and handle any missing values.
    - List all unique Country values in the dataset.

In [2]:
# Basic command
import numpy as np
import pandas as pd

In [3]:
# Open the File as a DataFram
df = pd.read_csv(r"./processed_microplastics.csv")

In [6]:
df.head(5)

,year,country,cheese,yoghurt,total_milk,fruits,refined_grains,whole_grains,nuts_and_seeds,total_processed_meats,...,fish,shellfish,eggs,total_salt,added_sugars,non-starchy_vegetables,potatoes,other_starchy_vegetables,beans_and_legumes,total_ug_per_kg
0,1990,Angola,0.191781,54.899739,96.602740,76.520548,481.297149,44.309838,2.849315,22.770109,...,53.013699,0.164384,1.041096,8.005259,32.547945,80.164384,8.109589,39.342466,19.835616,1043.279108
1,1990,Benin,0.054795,9.365946,18.410959,90.876712,534.256965,48.836323,19.561644,17.018264,...,18.794521,3.972603,2.849315,5.854497,8.246575,122.986301,0.000000,304.904110,21.178082,1241.656197
2,1990,Burkina Faso,0.273973,35.390618,56.027397,19.178082,213.170183,129.416119,28.465753,9.541329,...,4.684932,0.000000,6.767123,6.928378,9.534247,64.767123,2.219178,13.780822,32.520548,666.603927
3,1990,Central African Republic,0.000000,19.206478,48.000000,113.397260,285.035375,302.567776,23.506849,26.412094,...,13.917808,0.000000,1.123288,6.585071,19.698630,101.753425,0.575342,209.452055,12.821918,1237.339905
4,1990,Cote D'Ivoire,0.301370,2.220447,38.109589,37.013699,436.907598,25.220347,16.904110,2.459103,...,51.424658,0.493151,2.438356,9.660915,28.438356,151.150685,1.945205,676.575343,2.356164,1540.502458

In [6]:
# See the Columns
df.dtypes

year                          int64
country                      object
cheese                      float64
yoghurt                     float64
total_milk                  float64
fruits                      float64
refined_grains              float64
whole_grains                float64
nuts_and_seeds              float64
total_processed_meats       float64
unprocessed_red_meats       float64
fish                        float64
shellfish                   float64
eggs                        float64
total_salt                  float64
added_sugars                float64
non-starchy_vegetables      float64
potatoes                    float64
other_starchy_vegetables    float64
beans_and_legumes           float64
total_ug_per_kg             float64
dtype: object

In [4]:
# Check for any missing values - none found
df.isnull().sum()

# Drop NaN values - not necessary here because no such value was found
df = df.dropna()

In [17]:
# Print unique values for the column "country"
df["country"].unique()

array(['Angola', 'Benin', 'Burkina Faso', 'Central African Republic',
       "Cote D'Ivoire", 'Cameroon', 'Congo', 'Djibouti', 'Algeria',
       'Egypt', 'Ethiopia', 'Gabon', 'Ghana', 'Guinea', 'The Gambia',
       'Guinea-Bissau', 'Kenya', 'Lesotho', 'Morocco', 'Madagascar',
       'Mali', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi',
       'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Senegal', 'Chad', 'Togo',
       'Tunisia', 'Tanzania', 'Uganda', 'South Africa', 'Zambia',
       'Zimbabwe', 'Albania', 'Argentina', 'Antigua And Barbuda',
       'Australia', 'Austria', 'Bangladesh', 'Bulgaria', 'Bolivia',
       'Brazil', 'Barbados', 'Canada', 'Switzerland', 'China', 'Colombia',
       'Cuba', 'Germany', 'Dominica', 'Denmark', 'Dominican Republic',
       'Spain', 'France', 'United Kingdom', 'Greece', 'Grenada',
       'Hungary', 'Indonesia', 'India', 'Ireland', 'Iran', 'Iraq',
       'Iceland', 'Jordan', 'Japan', 'Cambodia', 'South Korea', 'Kuwait',
       'Laos', 'Saint Lucia', 'Sri Lanka', 'Mexico', 'Myanmar',
       'Mongolia', 'Malaysia', 'Netherlands', 'Norway', 'Pakistan',
       'Peru', 'Philippines', 'Portugal', 'Paraguay', 'Romania',
       'Saudi Arabia', 'Slovakia', 'Sweden', 'Thailand',
       'Trinidad And Tobago', 'Turkey', 'Uruguay', 'United States',
       'Venezuela', 'Vietnam', 'Belgium', 'Bosnia And Herzegovina',
       'Croatia', 'Luxembourg', 'Montenegro', 'Russia', 'Serbia',
       'Slovenia', 'Syria', 'Ukraine'], dtype=object)

> delete the questions which you will not answer, answer each question with a sufficient amount of blocks and document as needed.

## Beginner Task

- Overall Trends in Microplastic Consumption:
    - What is the average total_ug_per_kg across all countries and years in the dataset?
    - How has the global average total_ug_per_kg changed over the years (1990-2018)? Visualize this trend.

We use .mean() to get the average. I store it in a variable named 'avg_microplastic', just in case for when we need it again.
Then we print the average with the proper units.

In [ ]:
# average total_ug_per_kg across all countries and years
avg_microplastic = df['total_ug_per_kg'].mean()
print(f"Average total microplastic content: {avg_microplastic:.2f} Î¼g/kg")

np.float64(1600.6145743153152)

For the second question, we need to first group the years, and then calculate the average cosumptions for each year.

In [7]:
df

,year,country,cheese,yoghurt,total_milk,fruits,refined_grains,whole_grains,nuts_and_seeds,total_processed_meats,...,fish,shellfish,eggs,total_salt,added_sugars,non-starchy_vegetables,potatoes,other_starchy_vegetables,beans_and_legumes,total_ug_per_kg
0,1990,Angola,0.191781,54.899739,96.602740,76.520548,481.297149,44.309838,2.849315,22.770109,...,53.013699,0.164384,1.041096,8.005259,32.547945,80.164384,8.109589,39.342466,19.835616,1043.279108
1,1990,Benin,0.054795,9.365946,18.410959,90.876712,534.256965,48.836323,19.561644,17.018264,...,18.794521,3.972603,2.849315,5.854497,8.246575,122.986301,0.000000,304.904110,21.178082,1241.656197
2,1990,Burkina Faso,0.273973,35.390618,56.027397,19.178082,213.170183,129.416119,28.465753,9.541329,...,4.684932,0.000000,6.767123,6.928378,9.534247,64.767123,2.219178,13.780822,32.520548,666.603927
3,1990,Central African Republic,0.000000,19.206478,48.000000,113.397260,285.035375,302.567776,23.506849,26.412094,...,13.917808,0.000000,1.123288,6.585071,19.698630,101.753425,0.575342,209.452055,12.821918,1237.339905
4,1990,Cote D'Ivoire,0.301370,2.220447,38.109589,37.013699,436.907598,25.220347,16.904110,2.459103,...,51.424658,0.493151,2.438356,9.660915,28.438356,151.150685,1.945205,676.575343,2.356164,1540.502458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2018,Ukraine,3.095890,197.467540,434.027397,182.383562,281.855517,110.679415,7.452055,80.219005,...,29.260274,2.904110,47.534247,7.293989,165.260274,467.753425,362.712329,0.000000,4.164384,2449.652625
719,2018,Uruguay,4.849315,92.114737,526.273973,221.452055,367.075985,39.248261,3.890411,53.003204,...,21.863014,3.287671,31.479452,6.406854,150.849315,164.410959,77.369863,49.972603,8.191781,1926.873235
720,2018,United States,6.575342,28.422499,629.780822,285.452055,240.752817,43.196498,24.547945,143.165021,...,33.643836,27.342466,44.410959,8.256246,176.684932,313.315068,143.178082,11.561644,10.465753,2375.970526
721,2018,Venezuela,0.328767,23.940506,254.164384,192.739726,257.502833,13.814975,0.191781,39.370086,...,23.205479,4.191781,14.547945,5.843216,83.780822,136.767123,38.876712,65.671233,13.369863,1236.553584
722,2018,Vietnam,0.383562,17.581961,20.876712,233.424657,320.178816,6.677622,32.465753,22.411376,...,74.219178,28.054795,8.493151,3.289504,29.835616,457.863014,11.534247,13.342466,22.575342,1449.618314

- Top Food Contributors:
    - Which 3 food categories (product columns, e.g., fish, poultry, vegetables) show the highest average microplastic consumption (Î¼g/kg) across all countries and years?
    - Visualize the average microplastic content for the top 10 food categories.

- Country-Level Totals:
    - Which 5 countries have the highest average total_ug_per_kg over the entire period (1990-2018)?
    - Which 5 countries have the lowest average total_ug_per_kg?

- Initial Time-Series for a Food Category:
    - Choose one of the top 3 food categories identified in question 3. How has the microplastic content in this specific food category changed over time (1990-2018) globally? Visualize this trend.

## Intermediate Task

- Detailed Food Category Analysis:
    - For the top 3 food categories with the highest microplastic content, analyze their individual trends over time (1990-2018). Are some increasing more rapidly than others?
    - Compare the contribution of different food categories to the total_ug_per_kg in the earliest (1991) and latest (2018) years. Describe the shifts in contribution.

- Country-Specific Microplastic Profiles:
    - Select two countries with significantly different average total_ug_per_kg (one high, one low, from your beginner analysis).
    - For each selected country, visualize the breakdown of total_ug_per_kg by different food categories for the year 2018. Highlight the food categories contributing most to microplastic intake in these specific countries.

- Growth Rate Analysis:
    - Calculate the percentage increase in total_ug_per_kg from 1990 to 2018 for each country. Identify the top 5 countries with the highest growth rate in microplastic consumption.
    - Investigate which food categories are driving this growth in those top 5 countries.

- Correlation between Food Groups (Optional/Advanced):
    - Is there a correlation between microplastic content in different food groups? For example, do countries with high microplastic in fish also tend to have high microplastic in seafood or processed_foods? Use correlation matrices or scatter plots to explore.

### Public Health Implications & Recommendations (Qualitative):
- Based on your findings, what are 2-3 key insights you would present to the PurePlate Initiative regarding microplastic consumption?
- Propose potential policy recommendations or public awareness strategies that could help reduce human exposure to microplastics through diet, citing evidence from your analysis.

> Remember to provide clear visualizations and concise explanations for all your findings. Your analysis will contribute directly to a vital public health discussion!